### ISSUE TITLE
Standards compliance issue with DHCP MaxDHCPMessageSize option 

### ISSUE THREAD

**Issue by NameOfTheDragon** [netduino/Netduino.IP#3]
When monitoring Netduino traffic using Microsoft Message Analyzer, I noticed it was flagging up a compliance issue in the DHCP protocol.

![image](https://cloud.githubusercontent.com/assets/1268490/9146476/f02835fc-3d54-11e5-956d-79da46811e16.png)

According to RFC2132:

> "The code for this option is 57, and its length is 2. The minimum legal value is 576 octets".

I noticed that on Technet there is a documentation mistake, which says "The maximum legal value for this option is 576". That is incorrect, 576 is the _minimum_ value

I believe that is the link layer size and includes 64 octets header and 512 octets payload, that's the smallest link layer packet that hosts are supposed to accept.

**Comment by netduino** [comment]
Correct, thank you.  

The minimum value should be 576 (548 byte DHCP message + 20 byte IPv4 minimum header size + 8 byte UDP header size).  This is fixed for the Netduino.IP v1.0.1 release.
